# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  sources:
    - 'src/**/*'
    - 'Cargo.toml'
  tests:
    - 'benches/**/*'
    - 'tests/**/*'

tasks:
  check:
    command: 'cargo check'
    inputs:
      - '@globs(sources)'

  format:
    command: 'cargo fmt'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'

  lint:
    command: noop
    deps:
      - lint-clippy
      - lint-format

  lint-clippy:
    command: 'cargo clippy'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'

  lint-format:
    command: 'cargo fmt --check'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
