# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  dev:
    command: 'vite dev'
    local: true

  build:
    command: 'vite build'
    inputs:
      - '@globs(sources)'
      - '@globs(configs)'
      - '@globs(assets)'
    outputs:
      - 'dist/'
    options:
      runInCI: false

  preview:
    command: 'vite preview'
    local: true
